### ISSUE TITLE
[bug] Broken UI rendering with problem(s) of no titles

### ISSUE THREAD

**Issue by JennieHo-HPE** [JennieHo-HPE/Sapporo#13]
A very nasty bug...

How to reproduce:
1. Go to "Problem Configuration", and create a problem with an empty title (language doesn't matter)
2. Immediately, you'll find yourself not being able to visit other links/screens.

This issue affects only your own session, but other users/admins who are currently online.

**Comment by yilanhung** [comment]
Fix provided for validation: 6b5c5fd775af4ce8ae6fbe1f9f04ef959dc1dc1c

**Comment by JennieHo-HPE** [comment]
Verified
The admin user can operate the system after adding empty title problem
