### ISSUE TITLE
[Enhancement] Use NVM to manage different versions of Node for dev environment

### ISSUE THREAD

**Issue by JennieHo-HPE** [JennieHo-HPE/Sapporo#2]
Everybody is encouraged to use "NVM (https://github.com/nvm-sh/nvm)" for
managing different versions of Node for your dev environment.

`.nvmrc' is a file that contains a Node version string and is placed
under your project root for NVM to TURN ON a specific version of Node
runtime. Most importantly, it tells project users what version of Node
shall be used.

**Comment by yilanhung** [comment]
Not needed for the version of MeteorJS that this project is using.
