### ISSUE TITLE
Incorrect ordering of Ranking

### ISSUE THREAD

**Issue by joker78980** [JennieHo-HPE/Sapporo#24]
In the Ranking page. the ordering of Ranking is not correct. the record of tonysu1204 finish on 12/03, but the tony's record is displayed before the records finish on 12/1. 
![image](https://user-images.githubusercontent.com/43881241/146148389-949a2efc-0d11-4384-ba8d-81efdc279a8d.png)

**Comment by yilanhung** [comment]
99d026770c337a78d66548f61f65917420d40708
