### ISSUE TITLE
[bug] Update/Remove the versions in language selection

### ISSUE THREAD

**Issue by JennieHo-HPE** [JennieHo-HPE/Sapporo#6]
![image](https://user-images.githubusercontent.com/92622080/141922513-4b327a22-8644-4014-b25a-000af27849f5.png)

Rust 1.56
Golang 1.16

**Comment by JennieHo-HPE** [comment]
https://www.hpcodewars.com.tw/rules
Java 8 (OpenJDK 8u312)
Python 2.7
Python 3.10
C (gcc11.2)
C++ (gcc11.2)
Rust 1.56
Golang 1.16

Swift 5.5
-----------------
11/17

Java 8 
Python 2.7
Python 3.10
C 
C++ (C++14/17)
Rust 1.56
Golang 1.16
Swift 5.5

**Comment by JennieHo-HPE** [comment]
https://github.com/JennieHo-HPE/Sapporo/blob/master/imports/ui/admin/dockerConfig.jsx#L62

**Comment by yilanhung** [comment]
NOT A BUG. That is the default list built into the system for convenience. You always have to manually review and "configure" the list every year no matter what the default says.

**Comment by yilanhung** [comment]
So if you agree too, @JennieHo-HPE, close this issue as no-fix.

\# I'd kinda like this 'default list' to be populated from a config value, not hard-coded, but that'd a new feature request.

**Comment by JennieHo-HPE** [comment]
![image](https://user-images.githubusercontent.com/92622080/142234214-130dd9ea-9f2a-45a4-8fe4-a6d5fccc9c05.png)

The C++ 11 is supposed to be C++ ?
or we may seperate to C++14 and C++17

**Comment by yilanhung** [comment]
@JennieHo-HPE 
The admin has to update the language list. I believe what Jerry did was just populating the default list.
You can do that if you want.

![image](https://user-images.githubusercontent.com/94385515/142235583-69fd767d-e712-49e0-ab6c-65b0e9dac75b.png)

**Comment by yilanhung** [comment]
@JennieHo-HPE 
Yeah, I just updated "C++ 11" and made it "C++ 14". Also added "C++ 17". (logged in to the testing system as admin)

![image](https://user-images.githubusercontent.com/94385515/142241081-8ea5a61f-e8bd-49f5-a801-087f4a4ca507.png)

Looks like the language options on the editor screen appear in an order as they were entered by the admin. To get around that defect, we'll have to re-create the list in a sane order.

Or do you want to see it as a bug?

**Comment by JennieHo-HPE** [comment]
In end user's view, it's a bug in 2021.
However, the Sapporo is good
We may record this kind of items to 'regular task list' for every year.
