### ISSUE TITLE
[bug] The block "Codewar World Wide" is disabled

### ISSUE THREAD

**Issue by JennieHo-HPE** [JennieHo-HPE/Sapporo#7]
![image](https://user-images.githubusercontent.com/92622080/141948595-7e6c4836-8146-48c9-bfa6-5bc2add515fb.png)

**Comment by JennieHo-HPE** [comment]
**dashboard.jsx	imports\ui**

            title: 'Codewars World Wide',
            cols: 2,
            backgroundColor: 'rgba(0,80,160, 0.6)',
            icon: <IconButton><AboutIcon color="white" /></IconButton>,
            image: '/images/8.jpg',
            class:'hoverItem',  =>        Delete this line to remove the mouse hand cursor ?
            content: this.textContent('Everywhere')
        },
        
 or add a link to direct the global codewar sites?

**Comment by yilanhung** [comment]
@JennieHo-HPE, There's is no "global" CodeWars site, at least it's been like that for years as I could remember. Even if there were one now, I don't think it should be promoted here in the competition system. Who would bother to look at that when everybody is busy solving problems?

I vote to remove that box.

**Comment by yilanhung** [comment]
Now it's been repurposed to host "legal" links.

db7a349afad345bf6acc2847cec6554a25126f17

Issue closed.
